language:
  - python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      before_install:
          sudo apt-get install -y dpkg-dev build-essential python-dev libjpeg-dev libtiff5-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev libwebkitgtk-3.0-dev libgstreamer-plugins-base1.0-dev
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
          sudo apt-get install -y dpkg-dev build-essential python-dev libjpeg-dev libtiff5-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev libwebkitgtk-3.0-dev libgstreamer-plugins-base1.0-dev
      script:
        - set -e  # If any of the following steps fail, just stop at that point.
        - make -C docs html  # Build the documentation.
        - pip3 install doctr
        - doctr deploy --built-docs docs/build/html .  # Publish the documentation.
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      # https://blog.travis-ci.com/2018-10-11-windows-early-release
      before_install:
          sudo apt-get install -y dpkg-dev build-essential python-dev libjpeg-dev libtiff5-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev libwebkitgtk-3.0-dev libgstreamer-plugins-base1.0-dev
    - name: "Python 3.7.5 on macOS, xcode11.6"
      os: osx
      osx_image: xcode11.6  # Python 3.7.5 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.7.5 on macOS, xcode11.2"
      os: osx
      osx_image: xcode11.2  # Python 3.7.5 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.7.5 on macOS, xcode10"
      os: osx
      osx_image: xcode10  # Python 3.7.4 running on macOS 10.13.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    - name: "Python 3.6 on macOS, xcode10"
      os: osx
      osx_image: xcode10  # Python 3.7.4 running on macOS 10.13.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      python: 3.6         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
    # - name: "Python 3.7.4 on Windows"
    #   os: windows           # Windows 10.0.17134 N/A Build 17134
    #   language: shell       # 'language: python' is an error on Travis CI Windows
    #   # python: 3.7         # 'python:' is ignored on Travis CI Windows
    #   before_install:
    #     - choco install python --version 3.7.4
    #     - python --version
    #     - python -m pip install --upgrade pip
    #     - pip3 install --upgrade pytest
    #     - pip3 install codecov
    #     - pip3 install opencv-python-headless
    #     - pip3 install opencv-contrib-python-headless
    #   env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    # - name: "Python 3.8.0 on Windows"
    #   os: windows           # Windows 10.0.17134 N/A Build 17134
    #   language: shell       # 'language: python' is an error on Travis CI Windows
    #   # python: 3.7         # 'python:' is ignored on Travis CI Windows
    #   before_install:
    #     - choco install python --version 3.8.0
    #     - python --version
    #     - python -m pip install --upgrade pip
    #     - pip3 install --upgrade pytest
    #     - pip3 install opencv-python-headless
    #     - pip3 install opencv-contrib-python-headless
    #   env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  # Install this package and the packages listed in requirements.txt.
  - pip3 install --upgrade pip
  - pip3 install . #pip install --upgrade pip
  # Install extra requirements for running tests and building docs.
  - pip3 install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  #turn flake8 on when all formating issues are fixed and understood.
  # - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).

notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
      # Doctr deploy key for vstadnytskyi/dataq-di-2008
      - secure: "fIG1qGYh7PQ+lLx5kGcgnfiEfHQwAtTbevqq2exglp5Sy5c067KUYVAofyboJnWnBqaWOdsyn6l6vV1AkU5IhkQ4+Ie+mxQ4HnKadrWzHHi4KQi8YoohFXZuBXLOj9vIWYWq/99Xe1mhGbtP02OMFDB+3e5OR6u1Dm0o2FG3vINLLYuM6bxWRixKBk4MrPDDTRHOwzCR/DkcSoEE1jKueoqL0HiDZ11+wi6gwMiMgplyVHl5A7sivN3QBuackF+LcmOjzOcJm8zNM7wQpN0wlBlXJ0e+4b9qOz3qSBOOTQI+2gAZuigj8V1FRXOZOuOoJ3X+RE5+hKn6ct5vwUBeldEn0aawt77BsXpV6s2IScZF1GyH+cOB9WlYME/fnTZtc14UC4CvtZys5e9MTt3ud9m33E50M2Vy1dFWsp94y0Fa5xrAHNmAnkraXM4POlKkt2rrWw25MnTgBx+aAyIpO3IJFt0yqZEHt3Dt8J27y3QnmKWvSVTY8Nxzh53vdk2Gsb9f5AgP7X9ZCZjVeOB8vc+x8kcSNGg1yBaCGX2oUjMCwczi8KJ2PkDSdIvhZ+q4S5Wfp4FxQ4lzCLGW8+LL3/S1aaQF27xeQMISgKe2z3u3KaOGXH1//8NwsV+J87FNMoW5/2LqdiXAZa7fWwnTR37ow2dJUuI25hSVG4/RiLE="
